--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: appointments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    appointment_date date NOT NULL,
    arrival_time timestamp(6) without time zone,
    payment_status character varying(255) NOT NULL,
    reason text NOT NULL,
    status character varying(255) NOT NULL,
    time_block character varying(255) NOT NULL,
    doctor_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    specialty_id bigint NOT NULL,
    CONSTRAINT appointments_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT appointments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_VALIDATION'::character varying, 'SCHEDULED'::character varying, 'IN_CONSULTATION'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'NO_SHOW'::character varying])::text[]))),
    CONSTRAINT appointments_time_block_check CHECK (((time_block)::text = ANY ((ARRAY['MORNING'::character varying, 'AFTERNOON'::character varying, 'FULL_DAY'::character varying])::text[])))
);


--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    action character varying(100),
    description text,
    entity_id bigint,
    entity_name character varying(100) NOT NULL,
    error_message text,
    execution_time_ms bigint,
    module character varying(50),
    new_value text,
    old_value text,
    operation_type character varying(255) NOT NULL,
    request_method character varying(10),
    request_params text,
    request_url character varying(255),
    session_id character varying(100),
    status boolean NOT NULL,
    user_agent character varying(255),
    user_id bigint,
    user_ip character varying(50),
    username character varying(100),
    CONSTRAINT audit_logs_operation_type_check CHECK (((operation_type)::text = ANY ((ARRAY['CREATE'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying, 'LOGIN'::character varying, 'LOGOUT'::character varying, 'ACCESS'::character varying, 'EXPORT'::character varying, 'IMPORT'::character varying, 'PAYMENT'::character varying, 'REFUND'::character varying, 'SYSTEM'::character varying, 'NOTIFICATION'::character varying, 'PRINT'::character varying, 'VIEW'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chatbot_conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chatbot_conversations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_by character varying(255) NOT NULL,
    actions_taken text,
    context text,
    entities_detected text,
    feedback_rating integer,
    feedback_text text,
    human_agent_id bigint,
    intent_detected character varying(255),
    ip_address character varying(255),
    is_handled_by_human boolean,
    is_successful boolean NOT NULL,
    knowledge_base_entries_used text,
    query text NOT NULL,
    response text NOT NULL,
    response_time_ms bigint,
    session_id character varying(255) NOT NULL,
    source character varying(255),
    transferred_at timestamp(6) without time zone,
    user_agent character varying(255),
    user_id bigint
);


--
-- Name: chatbot_conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chatbot_conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chatbot_conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chatbot_knowledge_base; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chatbot_knowledge_base (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_by character varying(255) NOT NULL,
    answer text NOT NULL,
    category character varying(255),
    data_type character varying(255) NOT NULL,
    external_reference character varying(255),
    is_active boolean NOT NULL,
    keywords character varying(255) NOT NULL,
    metadata text,
    priority integer NOT NULL,
    question character varying(255) NOT NULL,
    related_entity_id bigint,
    related_entity_type character varying(255),
    subcategory character varying(255),
    success_rate double precision NOT NULL,
    topic character varying(255) NOT NULL,
    usage_count integer NOT NULL,
    CONSTRAINT chatbot_knowledge_base_data_type_check CHECK (((data_type)::text = ANY ((ARRAY['STRING'::character varying, 'INTEGER'::character varying, 'DECIMAL'::character varying, 'BOOLEAN'::character varying, 'DATE'::character varying, 'TIME'::character varying, 'DATETIME'::character varying, 'JSON'::character varying, 'HTML'::character varying, 'MARKDOWN'::character varying, 'XML'::character varying, 'URL'::character varying, 'EMAIL'::character varying, 'PHONE'::character varying, 'OBJECT_ID'::character varying])::text[])))
);


--
-- Name: chatbot_knowledge_base_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chatbot_knowledge_base ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chatbot_knowledge_base_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor_availability; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctor_availability (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    day_of_week integer NOT NULL,
    is_available boolean NOT NULL,
    max_patients integer NOT NULL,
    time_block character varying(255) NOT NULL,
    doctor_id bigint NOT NULL,
    CONSTRAINT doctor_availability_time_block_check CHECK (((time_block)::text = ANY ((ARRAY['MORNING'::character varying, 'AFTERNOON'::character varying, 'FULL_DAY'::character varying])::text[])))
);


--
-- Name: doctor_availability_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctor_availability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor_specialties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctor_specialties (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    certification_date date,
    is_primary boolean NOT NULL,
    doctor_id bigint NOT NULL,
    specialty_id bigint NOT NULL
);


--
-- Name: doctor_specialties_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctor_specialties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_specialties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctors (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    can_refer boolean NOT NULL,
    cmp_number character varying(255) NOT NULL,
    consultation_room character varying(255),
    contact_phone character varying(255),
    doctor_type character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    hire_date date,
    is_active boolean NOT NULL,
    is_external boolean NOT NULL,
    last_name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    profile_image character varying(255),
    second_last_name character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT doctors_doctor_type_check CHECK (((doctor_type)::text = ANY ((ARRAY['PRIMARY'::character varying, 'SPECIALIST'::character varying])::text[])))
);


--
-- Name: doctors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hospital_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hospital_settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_by character varying(255) NOT NULL,
    category character varying(255),
    data_type character varying(255) NOT NULL,
    description character varying(255),
    is_editable boolean NOT NULL,
    is_public boolean NOT NULL,
    setting_key character varying(255) NOT NULL,
    setting_value text NOT NULL,
    CONSTRAINT hospital_settings_data_type_check CHECK (((data_type)::text = ANY ((ARRAY['STRING'::character varying, 'INTEGER'::character varying, 'DECIMAL'::character varying, 'BOOLEAN'::character varying, 'DATE'::character varying, 'TIME'::character varying, 'DATETIME'::character varying, 'JSON'::character varying, 'HTML'::character varying, 'MARKDOWN'::character varying, 'XML'::character varying, 'URL'::character varying, 'EMAIL'::character varying, 'PHONE'::character varying, 'OBJECT_ID'::character varying])::text[])))
);


--
-- Name: hospital_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hospital_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hospital_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medical_attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medical_attachments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_by character varying(255) NOT NULL,
    content_type character varying(255) NOT NULL,
    description text,
    file_name character varying(255) NOT NULL,
    file_path character varying(255) NOT NULL,
    file_size bigint NOT NULL,
    file_type character varying(255) NOT NULL,
    is_public boolean,
    tags character varying(255),
    upload_date timestamp(6) without time zone NOT NULL,
    upload_source character varying(255) NOT NULL,
    medical_record_id bigint,
    patient_id bigint NOT NULL,
    CONSTRAINT medical_attachments_file_type_check CHECK (((file_type)::text = ANY ((ARRAY['PDF'::character varying, 'IMAGE'::character varying, 'DOCUMENT'::character varying, 'PRESCRIPTION'::character varying, 'LAB_RESULT'::character varying, 'XRAY'::character varying, 'ULTRASOUND'::character varying, 'MRI'::character varying, 'CT_SCAN'::character varying, 'AUDIO'::character varying, 'VIDEO'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT medical_attachments_upload_source_check CHECK (((upload_source)::text = ANY ((ARRAY['DOCTOR'::character varying, 'PATIENT'::character varying, 'SYSTEM'::character varying, 'LABORATORY'::character varying, 'ADMINISTRATIVE'::character varying])::text[])))
);


--
-- Name: medical_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medical_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medical_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medical_records (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255) NOT NULL,
    updated_by character varying(255) NOT NULL,
    allergies text,
    blood_pressure character varying(255),
    chief_complaint text NOT NULL,
    diagnosis text,
    followup_date timestamp(6) without time zone,
    followup_required boolean,
    heart_rate integer,
    height_cm double precision,
    is_referral_record boolean,
    notes text,
    oxygen_saturation integer,
    record_date timestamp(6) without time zone NOT NULL,
    referral_notes text,
    respiratory_rate integer,
    severity character varying(255),
    symptoms text,
    temperature double precision,
    treatment_plan text,
    weight_kg double precision,
    appointment_id bigint,
    doctor_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    CONSTRAINT medical_records_severity_check CHECK (((severity)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[])))
);


--
-- Name: medical_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medical_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patients (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    address text,
    allergies text,
    birth_date date NOT NULL,
    blood_type character varying(255),
    emergency_contact_name character varying(255),
    emergency_contact_phone character varying(255),
    first_name character varying(255) NOT NULL,
    gender character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    medical_history text,
    phone character varying(255) NOT NULL,
    reniec_verified boolean NOT NULL,
    second_last_name character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT patients_blood_type_check CHECK (((blood_type)::text = ANY ((ARRAY['A_POSITIVE'::character varying, 'A_NEGATIVE'::character varying, 'B_POSITIVE'::character varying, 'B_NEGATIVE'::character varying, 'AB_POSITIVE'::character varying, 'AB_NEGATIVE'::character varying, 'O_POSITIVE'::character varying, 'O_NEGATIVE'::character varying])::text[]))),
    CONSTRAINT patients_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: patients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_methods (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    active boolean,
    description character varying(500),
    display_order integer,
    gateway_code character varying(50),
    gateway_name character varying(50),
    logo_url character varying(500),
    name character varying(100) NOT NULL,
    processing_fee numeric(10,2),
    type character varying(255) NOT NULL,
    CONSTRAINT payment_methods_type_check CHECK (((type)::text = ANY ((ARRAY['CASH'::character varying, 'DIGITAL'::character varying, 'CARD'::character varying])::text[])))
);


--
-- Name: payment_methods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_methods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_methods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    amount numeric(10,2) NOT NULL,
    checkout_url character varying(500),
    payer_email character varying(150),
    payer_name character varying(150),
    payment_date timestamp(6) without time zone,
    payment_order_id character varying(100),
    processing_fee numeric(10,2),
    receipt_number character varying(50),
    status character varying(255) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    transaction_reference character varying(100),
    appointment_id bigint NOT NULL,
    payment_method_id bigint,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referrals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referrals (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    reason text,
    scheduled_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    new_appointment_id bigint,
    original_appointment_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    referring_doctor_id bigint NOT NULL,
    target_specialty_id bigint NOT NULL,
    CONSTRAINT referrals_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'SCHEDULED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: referrals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.referrals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.referrals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: specialties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.specialties (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    consultation_price numeric(10,2) NOT NULL,
    description text,
    discount_percentage numeric(5,2),
    is_active boolean NOT NULL,
    is_primary boolean NOT NULL,
    name character varying(100) NOT NULL,
    requires_referral boolean NOT NULL
);


--
-- Name: specialties_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.specialties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specialties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    dni character varying(8),
    email character varying(255),
    is_active boolean NOT NULL,
    last_login timestamp(6) without time zone,
    password_hash character varying(255),
    requires_activation boolean NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['PATIENT'::character varying, 'DOCTOR'::character varying, 'SPECIALIST'::character varying, 'RECEPTIONIST'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- PostgreSQL database dump complete
--

